/**
 * @file sprites.c
 * @brief Contains arrays of sprite pointers generated by this script run.
 */

#include "sprites.h"

// Array of all generated sprites
const lv_img_dsc_t* all_generated_sprites[] = {
    &sprite_3buttondungeon,
};

// Number of sprites in the array
const uint8_t all_generated_sprites_count = sizeof(all_generated_sprites) / sizeof(all_generated_sprites[0]);
